sudo: required

services:
  - docker

language: go

go:
  - 1.7

script:
  - go build github.com/PonyvilleFM/aura/cmd/aura
  - go install github.com/PonyvilleFM/aura/cmd/aura
  - go build github.com/PonyvilleFM/aura/cmd/aerial
  - go install github.com/PonyvilleFM/aura/cmd/aerial
  - curl -SsL https://github.com/erikh/box/releases/download/v0.4.1/box-0.4.1.linux.gz -o box.gz
  - gunzip box.gz && chmod +x ./box && rm box.gz
  - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD --email $DOCKER_EMAIL
  - ./box --no-tty multi ./build/aerial.rb ./build/aura.rb
  - docker tag pvfm/aerial pvfm/aerial:$TRAVIS_COMMIT
  - docker tag pvfm/aura pvfm/aura:$TRAVIS_COMMIT
  - docker push pvfm/aerial:$TRAVIS_COMMIT
  - docker push pvfm/aura:$TRAVIS_COMMIT
