language: go

go:
  - 1.x

script:
  - go build github.com/PonyvilleFM/aura/cmd/aura
  - go install github.com/PonyvilleFM/aura/cmd/aura
  - go build github.com/PonyvilleFM/aura/cmd/aerial
  - go install github.com/PonyvilleFM/aura/cmd/aerial
